# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('watched', models.BooleanField(default=False)),
                ('last_received', models.DateTimeField(verbose_name='date received')),
                ('last_success', models.DateTimeField(null=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Feedrun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status_code', models.CharField(max_length=200)),
                ('status_summary', models.CharField(max_length=200)),
                ('run_link', models.CharField(max_length=200)),
                ('console_link', models.CharField(max_length=200)),
                ('notification_sent', models.BooleanField(default=False)),
                ('feed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n4f2.FeedProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='feedprofile',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='n4f2.Site'),
        ),
    ]
