# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedruns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField()),
                ('site_name', models.CharField(max_length=200)),
                ('feed_profile', models.CharField(max_length=200)),
                ('feed_name', models.CharField(max_length=200)),
                ('status_code', models.CharField(max_length=200)),
                ('status_summary', models.CharField(max_length=200)),
                ('last_received', models.DateTimeField(verbose_name='date received')),
                ('last_success', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
