# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n4f2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ignoredsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
            ],
        ),
    ]
