# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n4f2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedprofile',
            name='last_received',
            field=models.DateTimeField(null=True, verbose_name='date received'),
        ),
    ]
