# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n4f2', '0003_seed_ignorelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedrun',
            name='run_link',
            field=models.CharField(default='url', max_length=200),
            preserve_default=False,
        ),
    ]
