# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:58
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):
    
    dependencies = [
        ('n4f2', '0005_feedrun_console_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedrun',
            name='notification_sent',
            field=models.BooleanField(),
            preserve_default=False,
        ),
    ]