version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
  web:
    build: .
    command: >
      /bin/bash -c "
        while ! nc -z db 5432;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
        python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    